# Generated by Django 5.2.1 on 2025-07-05 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_emailverification_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
